# Generated by Django 5.1.3 on 2024-11-22 18:00

import collector.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=collector.models.user_directory_path)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('plot', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=200)),
                ('coverage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.observation')),
            ],
        ),
    ]
