# Generated by Django 5.1.3 on 2024-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_species_alter_observation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='block',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='cutting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='fertilization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='row',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='plot',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
