# Generated by Django 5.1.3 on 2024-11-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_observation_chlorophyl_observation_eat_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationspecies',
            name='species_name',
        ),
    ]
