# Generated by Django 5.1.3 on 2024-11-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_remove_observationspecies_species_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationspecies',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.species'),
        ),
    ]
