# Generated by Django 5.1.3 on 2024-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_remove_observationspecies_species_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-create_date'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='observationspecies',
            options={'verbose_name': 'ObservationSpecies', 'verbose_name_plural': 'ObservationSpecies'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['name'], name='collector_s_name_4e186e_idx'),
        ),
    ]
