# Generated by Django 5.1.3 on 2024-11-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_alter_observation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Plot',
                'verbose_name_plural': 'Plots',
            },
        ),
        migrations.CreateModel(
            name='PlotProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.plot')),
            ],
            options={
                'verbose_name': 'Plot Property',
                'verbose_name_plural': 'Plot Properties',
            },
        ),
    ]
