# Generated by Django 5.1.3 on 2024-11-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_plot_plotproperties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='plot',
        ),
        migrations.AddField(
            model_name='plot',
            name='source',
            field=models.CharField(default='system', max_length=20),
        ),
    ]
