# Generated by Django 5.1.3 on 2024-11-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_remove_observation_plot_plot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.plot'),
        ),
    ]
