# Generated by Django 5.1.3 on 2024-11-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_observation_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationspecies',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationspecies', to='collector.observation'),
        ),
    ]
