# Generated by Django 5.1.3 on 2024-11-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_observationspecies_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
